<?php

namespace AppBundle\Repository;

/**
 * BudgetPercentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BudgetPercentRepository extends \Doctrine\ORM\EntityRepository
{
}
