<?php

namespace AppBundle\Repository;

/**
 * MonthlyAssetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MonthlyAssetRepository extends \Doctrine\ORM\EntityRepository
{
}
