<?php

namespace AppBundle\Repository;

/**
 * MonthlyCostsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MonthlyCostsRepository extends \Doctrine\ORM\EntityRepository
{
}
