let pointsToDispose = 100;
let defaultValue = 10;
let formId = `input[name*='x']`;
let idStart; 
let formNames;

//get first part of id generated by Symfony
function findStartOfFormId(formId) {
	idStart = document.querySelector(`${formId}`).getAttribute('id');	
	let res = idStart.split("_");
    res.pop();//cut "day"
    return res.join('_');
}

idStart = findStartOfFormId(formId);

//get all form inputs from page
function findDateForms(formId) {
    let inputs = document.querySelectorAll(`${formId}`); 
    let idData;
    let formNames = [];
    if (inputs.length > 0) { 
        for (let i=0; i < inputs.length; i++) { 
			//set default value to fields and decrease value of pointsToDispose
			inputs[i].value = defaultValue;  
			pointsToDispose -= defaultValue;  
			//set all fields id's to array    
			idData = inputs[i].getAttribute('id');    
            formNames[i] = idData;  
        }         
    }
    return formNames;
}

formNames = findDateForms(formId);

//set default value of points after first disposal
document.querySelector('#pointsToDispose').innerHTML = pointsToDispose;

//functions to dispose points by user
function changeValue(changeType, name) {

	let valueOfField = parseInt(document.querySelector(`#${idStart}_x${name}`).value);
	pointsToDispose = parseInt(pointsToDispose);
	//let fields values to be > 0
	if (changeType === 'Minus') {
		if (valueOfField > 0) {
			pointsToDispose = pointsToDispose + 1;		
			document.querySelector(`#${idStart}_x${name}`).value = valueOfField - 1;
		}
	} else {
		if (parseInt(pointsToDispose) > 0) {
			pointsToDispose = pointsToDispose - 1;
			document.querySelector(`#${idStart}_x${name}`).value =  valueOfField + 1;
		}
	}
	//set value of points
	document.querySelector('#pointsToDispose').innerHTML = pointsToDispose;	
}
