let pointsToDispose = 100;
let formId = `input[name*='_form']`;
let idStart; 
let formNames;
let valueOfField;
let valueFromDB;

//get first part of id generated by Symfony
function findStartOfFormId(formId) {
	idStart = document.querySelector(`${formId}`).getAttribute('id');		
	let res = idStart.split("_");
	name = res.pop();//cut form input name
    return res.join('_');
}

idStart = findStartOfFormId(formId);

//decrease value of pointsToDispose by data from db (passed into form)
function pointsToDisposeCheck(formId) {
	let inputs = document.querySelectorAll(`${formId}`); 	
    if (inputs.length > 0) { 
        for (let i=0; i < inputs.length; i++) { 
			//get only corretc fields values			
			if ( !isNaN(inputs[i].value) && inputs[i].value <= 100) {
				valueFromDB = inputs[i].value;
				pointsToDispose -= valueFromDB;
			}		 
        }         
    }
    return null;
};

pointsToDisposeCheck(formId);

//set default value of points after first disposal
document.querySelector('#pointsToDispose').innerHTML = pointsToDispose;

//functions to dispose points by user
function changeValue(changeType, name) {
	//check value of field and if it's empty string set value to 0
	if (document.querySelector(`#${idStart}_${name}`).value === '') {
		document.querySelector(`#${idStart}_${name}`).value = 0;
	}

	valueOfField = document.querySelector(`#${idStart}_${name}`).value;

	pointsToDispose = parseInt(pointsToDispose);
	//let fields values to be > 0
	if (changeType === 'Minus') {
		if (valueOfField > 0) {
			pointsToDispose = pointsToDispose + 1;		
			document.querySelector(`#${idStart}_${name}`).value = parseInt(valueOfField) - 1;
		}
	} else {
		if (parseInt(pointsToDispose) > 0) {
			pointsToDispose = pointsToDispose - 1;
			document.querySelector(`#${idStart}_${name}`).value =  parseInt(valueOfField) + 1;
		}
	}
	//set value of points
	document.querySelector('#pointsToDispose').innerHTML = pointsToDispose;	
}
