AppBundle\Entity\MonthlyCosts:
    type: entity
    manyToOne:
        user:
            targetEntity: User
            inversedBy: monthlyCost
            joinColumn:
                name: user_id
                referencedColumnName: id
        costType:
            targetEntity: CostType
            inversedBy: monthlyCost
            joinColumn:
                name: costType_id
                referencedColumnName: id
    table: null
    repositoryClass: AppBundle\Repository\MonthlyCostsRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        month:
            type: integer
        year:
            type: integer
        addDate:
            type: datetime
        costValue:
            type: integer
        name:
            type: string
    lifecycleCallbacks: {  }
